import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "../../app/globals.css";
import { Toaster } from "react-hot-toast";


const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HABIB-STORE LOGIN",
  description: "Generated by create next app",
  icons: "@/app/favicon.ico",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>{/* <link rel="icon" href="./favicon.ico" /> */}</head>
      <body className={inter.className + "bg-primary dark"}>
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          containerClassName=""
          containerStyle={{}}
          toastOptions={{
            // Define default options
            className: '',
            duration: 3000,
            style: {
              background: '#363636',
              color: '#fff',
            },

            // Default options for specific types
            success: {
              duration: 3000,
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
